name: Generate updated ICS Files

permissions:
  contents: write

on:
  schedule:
    - cron: '0 18 * * *' # Runs daily around midnight
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install poetry
        poetry config virtualenvs.create false
        poetry install --no-root

    - name: Run generate.py to update ICS files
      run: |
        python clearing_day_ics/src/clearing-day-ics/generate.py gh_pages_files

    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Update ICS files"